//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjetosDeNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int IdProducto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdRubro { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<int> IdUnidadMedida { get; set; }
        public Nullable<float> PVP { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
    }
}
